document.writeln("<div style=\'display:none\'>");
document.writeln("<!-- 百度统计 -->");
document.writeln("<script>");
document.writeln("var _hmt = _hmt || [];");
document.writeln("(function() {");
document.writeln("  var hm = document.createElement(\'script\');");
document.writeln("  hm.src = \'https://hm.baidu.com/hm.js?5757c88f155d23f476742f9311c252b1\';");
document.writeln("  var s = document.getElementsByTagName(\'script\')[0]; ");
document.writeln("  s.parentNode.insertBefore(hm, s);");
document.writeln("})();");
document.writeln("</script>");
document.writeln("<!-- 谷歌统计 -->");
document.writeln("<!-- Global site tag (gtag.js) - Google Analytics -->");
document.writeln("<script async src=\'https://www.googletagmanager.com/gtag/js?id=G-FTXPH8S11W\'></script>");
document.writeln("<script>");
document.writeln("  window.dataLayer = window.dataLayer || [];");
document.writeln("  function gtag(){dataLayer.push(arguments);}");
document.writeln("  gtag(\'js\', new Date());");
document.writeln("");
document.writeln("  gtag(\'config\', \'G-FTXPH8S11W\');");
document.writeln("</script>");
document.writeln("</div>");
document.writeln("<!-- 谷歌广告 -->");
document.writeln("<script async src=\'https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-7149471029165994\'");
document.writeln("     crossorigin=\'anonymous\'></script>");
document.writeln("<!-- 谷歌AMP广告 -->");
document.writeln("  <script async custom-element=\'amp-auto-ads\'");
document.writeln("        src=\'https://cdn.ampproject.org/v0/amp-auto-ads-0.1.js\'>");
document.writeln("</script>");
document.writeln("<amp-auto-ads type=\'adsense\'");
document.writeln("        data-ad-client=\'ca-pub-7149471029165994\'>");
document.writeln("</amp-auto-ads>");
document.writeln("<!-- 百度广告 -->");
document.writeln("<script type=\'text/javascript\' src=\'//cpro.baidustatic.com/cpro/ui/c.js\' async=\'async\' defer=\'defer\' >");
document.writeln("</script>");
document.writeln(" <script type=\'text/javascript\' src=\'//cpro.baidustatic.com/cpro/ui/cm.js\' async=\'async\' defer=\'defer\' >");
document.writeln("    </script>");
document.writeln("</div>");